### PR TITLE
Use utf-16 to inz constant chars to be source ccsid independent on build

### PR DESCRIPTION
**Pull request by jimoibm**
@kadler Here is the code changes for #32 .Please help take a look.

### CODE REVIEW

**Comment by jimoibm** [comment]
@kadler TGTCCSID is not supported in CRTRPGMOD. The latest committed build script has this error.

> bash-4.4$ make
(system -q 'CHKOBJ QXMLSERV *LIB' || system -q 'CRTLIB QXMLSERV') && touch QXMLSERV.lib
system "CRTRPGMOD MODULE(QXMLSERV/xmlmain) SRCSTMF('src/xmlmain.rpgle') DBGVIEW(*SOURCE) REPLACE(*YES) TGTCCSID(37)" > xmlmain.log 2> xmlmain.msg && rm xmlmain.log xmlmain.msg || touch xmlmain.failed
test ! -e xmlmain.msg || cat xmlmain.msg
CPD0043: Keyword TGTCCSID not valid for this command.
CPF0006: Errors occurred in command.
test ! -e xmlmain.log || ./parse.sh xmlmain.log
if [ -e xmlmain.failed ]; then rm xmlmain.failed; exit 1; fi
make: *** [Makefile:97: xmlmain.module] Error 1

**Comment by kadler** [comment]
You are missing a PTF: https://www.ibm.com/developerworks/community/wikis/home#!/wiki/We13116a562db_467e_bcd4_882013aec57a/page/Compile%20RPG%20from%20Unicode%20source%20-%20new%20TGTCCSID%20parameter%20in%207.1%2C%207.2%2C%207.3

**Comment by jimoibm** [comment]
@kadler Thanks! But looks like the exportsrc change was committed. There are missing procedures like RUNASCII..

**Comment by kadler** [comment]
Yes, I realized that later afterward. We'll need to update it.

**Comment by jimoibm** [comment]
@kadler Is my code OK to move in? Thanks!

**Comment by kadler** [comment]
Sorry, I won't have time to review until next week.

**Comment by jimoibm** [comment]
Thanks @kadler ! I will create another request from ICC... want us to extend the CGI pwd length in 10 chars. Will also have that in the latest ptf if possible.

**Comment by jimoibm** [comment]
@kadler Is this change OK to be move in?

**Pull request merged**
